apiVersion: 1

datasources:
  - name: elasticsearch-v7
    type: elasticsearch
    access: proxy
    database: "kafka_log_demo"
    url: http://elasticsearch:9200
    jsonData:
      timeField: "currentTime"
      esVersion: 70